import = [
  "~/.config/alacritty/rose-pine.toml",
]
live_config_reload = true

[window]
decorations = "Full"
opacity = 0.95
blur = true
option_as_alt = "Both"

[font]
normal = {family="Monaspace Krypton", style="Regular"}
bold = {family="Monaspace Krypton", style="Bold"}
italic = {family="Monaspace Krypton", style="Italic"}
size = 12
offset = {x = 0, y = 15}

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Never" }
unfocused_hollow = true
