theme = "rose_pine_moon"

[editor]
bufferline="always"
color-modes=true
line-number="relative"
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "file-name", "version-control"]
