
[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }
