endpoint: https://adfenix.atlassian.net
user: damoon.rashidi@adfenix.com
password-source: keyring
custom-commands:
  - name: mine
    help: display issues assigned to me
    script: |-
      {{jira}} list --query "resolution = unresolved and assignee=currentuser() ORDER BY created"
  - name: claim
    help: Assign an issue to me
    args:
      - name: ISSUE
        required: true
    script: |-
      {{jira}} take {{args.ISSUE}} "damoon.rashidi"
  - name: sprint-add
    help: add issue to active sprint for project
    args:
      - name: ISSUE
        required: true
    script: |
      board_id=$({{jira}} req "/rest/agile/1.0/board?projectKeyOrId=$JIRA_PROJECT" --gjq values.2.id)
      sprint_id=$({{jira}} req "/rest/agile/1.0/board/$board_id/sprint?state=active" --gjq values.0.id)
      {{jira}} req -M POST "/rest/agile/1.0/sprint/$sprint_id/issue" "{\"issues\":[\"{{args.ISSUE}}\"]}" >/dev/null
      echo "{{args.ISSUE}} added to current sprint"
